# Generated by Django 4.1.2 on 2022-10-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
