# Generated by Django 4.1.2 on 2022-10-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0002_rename_project_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
