# Generated by Django 4.1.2 on 2022-10-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0005_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='phone',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectDevelopers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracker.project')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracker.developer')),
            ],
        ),
    ]
