# Generated by Django 4.1.2 on 2022-10-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0006_developer_phone_projectdevelopers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDevelopers',
            new_name='ProjectDeveloper',
        ),
    ]
