# Generated by Django 4.1.2 on 2022-10-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0008_rename_project_projectdeveloper_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='project_tracker.developer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to='project_tracker.developer'),
        ),
    ]
