# Generated by Django 4.1.2 on 2022-10-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0009_alter_ticket_developer_alter_ticket_submitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.PROTECT, to='project_tracker.developer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectdeveloper',
            unique_together={('project', 'developer')},
        ),
    ]
