# Generated by Django 4.1.3 on 2022-12-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0010_alter_developer_options_project_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdeveloper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='project_tracker.project'),
        ),
        migrations.CreateModel(
            name='TicketDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracker.developer')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='project_tracker.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'developer')},
            },
        ),
    ]
