# Generated by Django 4.1.3 on 2022-12-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0011_alter_projectdeveloper_project_ticketdeveloper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='developer',
        ),
    ]
