# Generated by Django 4.1.3 on 2022-12-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0014_alter_developer_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time_Created',
            new_name='time_created',
        ),
    ]
