# Generated by Django 4.1.3 on 2022-12-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0015_rename_time_created_comment_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment',
            new_name='comment',
        ),
    ]
