# Generated by Django 4.1.3 on 2022-12-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0016_rename_coment_comment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'permissions': [('view_projects', 'Can view all projects')]},
        ),
        migrations.AlterField(
            model_name='projectdeveloper',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_developers', to='project_tracker.developer'),
        ),
    ]
