# Generated by Django 4.1.3 on 2022-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0017_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='role',
            field=models.CharField(default='Developer', max_length=255),
        ),
    ]
