# Generated by Django 4.1.3 on 2022-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0018_alter_project_options_projectdeveloper_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdeveloper',
            name='admin_permission',
            field=models.BooleanField(default=False),
        ),
    ]
